version: '3'

services:
  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=d.sierra@focal.com
      - PGADMIN_DEFAULT_PASSWORD=unmotdepassefocal
      - PGADMIN_LISTEN_PORT=8091
    network_mode: host

  app:
    container_name: "app"
    build: ./backend/
    volumes:
      - ./backend:/code
    restart: always
    network_mode: host

  backend-dev:
    container_name: "backend-dev"
    build:
      context: ./backend/
      dockerfile: "./dockerfile-dev/Dockerfile"
    volumes:
      - ./backend:/code
    restart: always
    network_mode: host

  frontend:
    container_name: "frontend"
    build: ./frontend/
    network_mode: host
