[entryPoints]
  [entryPoints.web]
  address = ":8082"
[entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.traefik]
  address=":8084"
  [entryPoints.websecure]
  address = ":8083"
[api]
dashboard = true
insecure = true

[log]
level = "DEBUG"

[providers]
  [providers.docker]
  exposedByDefault = false  
  [providers.file]
    filename = "/traefik/traefik.config.toml"
