"""New Migration

Revision ID: d3e0f7242459
Revises: 
Create Date: 2023-06-21 14:53:03.792841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e0f7242459'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hoursuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hoursuser_email'), 'hoursuser', ['email'], unique=True)
    op.create_index(op.f('ix_hoursuser_id'), 'hoursuser', ['id'], unique=False)
    op.create_index(op.f('ix_hoursuser_username'), 'hoursuser', ['username'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capitalization', sa.Boolean(), nullable=True),
    sa.Column('entity', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_classification'), 'project', ['classification'], unique=False)
    op.create_index(op.f('ix_project_division'), 'project', ['division'], unique=False)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worked_hours', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['hoursuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_register_id'), 'register', ['id'], unique=False)
    op.create_index(op.f('ix_register_worked_hours'), 'register', ['worked_hours'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_register_worked_hours'), table_name='register')
    op.drop_index(op.f('ix_register_id'), table_name='register')
    op.drop_table('register')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_division'), table_name='project')
    op.drop_index(op.f('ix_project_classification'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_hoursuser_username'), table_name='hoursuser')
    op.drop_index(op.f('ix_hoursuser_id'), table_name='hoursuser')
    op.drop_index(op.f('ix_hoursuser_email'), table_name='hoursuser')
    op.drop_table('hoursuser')
    # ### end Alembic commands ###
